### ISSUE TITLE
Fehlende Elemente im Template

### ISSUE THREAD

**Issue by nielsgeo** [elb-min-uhh/elearn.js#3]
In der aktuellen Version vom elearn.js-Template fehlen die Textblöcke, bei denen die Symbole für Web, Hinweis und Aufgabe eingeblendet werden. In einer früheren Version war das mit drin. Was evtl. auch ergänzt werden könnte, ist das Einbinden von einem "normalen" Bild, also nicht als Galerie.
Grüße
Niels

**Comment by westarne** [comment]
Ich bin mir nicht sicher, ob das eventuell nur eine Begleiterscheinung eines Updates war.

![image](https://user-images.githubusercontent.com/15111918/46602511-b906ea00-caf0-11e8-84b6-8465f1929a1c.png)

Sollten diese Blöcke gemeint sein, finde ich diese sowohl unter /Template/index.html als auch /Examples/Markdown/elearn_template.md.
