### ISSUE TITLE
Vorschlag: Slideshow-Option "Rückwärts-Loop" 

### ISSUE THREAD

**Issue by nielsgeo** [elb-min-uhh/elearn.js#4]
Wenn bei einer slideshow class="slider preview-nav **loop**" eingestellt wird, können die Bilder in einer Schleife angezeigt werden. 
Wird in der Slideshow z.B. eine Schritt-für-Schritt-Anleitung präsentiert, ist nicht unbedingt deutlich, wann das Ende der Bilderstrecke erreicht ist, da es übergangslos mit dem ersten Bild wieder losgeht.
Schön wäre, wenn es eine zusätzliche Option gäbe, bei der statt des Loops nach dem letzten Bild zum ersten "zurückgespult" wird. Ich erinnere, das dies in einer früheren Version bei der Einstellung "loop" der Fall war.

**Comment by westarne** [comment]
Das ist ein interessanter Vorschlag. Werde ich ergänzen.

**Comment by westarne** [comment]
Wurde umgesetzt. Statt der Klasse `loop` muss hierfür `back-loop` verwendet werden, dann ist die Funktionalität wie in frühen elearn.js Versionen.
