### ISSUE TITLE
Größe hover-info-Box

### ISSUE THREAD

**Issue by nielsgeo** [elb-min-uhh/elearn.js#5]
Bin nicht sicher, ob das hier der richtige Platz ist, die Antwort wäre wohl eher was fürs wiki oder template.

Gibt es eine Möglichkeit, im html ohne für Laien umständliche Eingriffe in .css oder .js die Größe einer hover-info-Box einzustellen? Hintergrund: Wenn ich dort ein Bild einbinde (was super klappt!) möchte ich es evtl. größer anzeigen lassen, als die offenbar fest voreingestellte maximale Größe der Box.

Hier ein Beispiel-Code:
```
Denke daran, zum Schluss die veränderte Datei zu speichern (Menü oder Strg+s). Ignoriere auch hierbei den
	<div class="hover-info" style="width: XXpx">
		Kompatibilitäts-Hinweis
		<div><img alt="Speichern csv Eigenschaften" src="assets/img/speichern_eigenschaften.png" style="width:50%"/>
		</div>
	</div>
	von Excel und bestätige mit ,,Ja&rdquo;.
```
Es wäre gut, wenn man bei `class="hover-info" style="width: XXpx` eine width oder size o.ä. in px oder % angeben könnte. Bei `<img ....` kann man die Größe des Bildes innerhalb der immer gleich großen Box nur bis max. 100% einstellen.

**Comment by westarne** [comment]
Moin, nach aktuellem Stand werden die Hover-Infos komplett automatisiert skaliert. Das bedeutet, dass ein solcher Block maximal 50% der Sectionbreite groß sein kann, damit er unabhängig von der Positionierung niemals über den Seitenrand hinausgeht. Das ganze ließe sich allerdings erweitern.

Ich könnte beispielsweise eine Klasse `full` ergänzen (`div.hover-info.full`), die es erlaubt auch 100% der Sectionbreite einzunehmen und entsprechend anders positioniert zu werden. 
Ich würde das ganze als zukünfitges Feature zeitnah umsetzen und hier verlinken.

**Comment by westarne** [comment]
Ich habe das Ganze jetzt wiefolgt umgesetzt (Wiki Eintrag folgt unter: https://github.com/elb-min-uhh/elearn.js/wiki/Additional-Elements in Kürze):

Ergänzt man einen `div.hover-info` um die Klasse `full` wie hier,

```html
<div class="hover-info full" id="info-full-1" data-width="80%" data-full-width="440">
    Beispiel
    <div>
        Beispiel Info. Hier können ggf. ein langer Text oder auch Bilder ergänzt werden.
    </div>
</div>
```

würde der `.hover-info-block`, der beim Hovern angezeigt wird, grundlegend die volle Sectionbreite ausnutzen, wenn nötig. In diesem Beispiel habe ich noch die Werte `data-width` und `data-full-width` ergänzt, die die Funktionalität erweitern:

`data-width` gibt einen Wert der maximalen Breite der angezeigten Info an. Hier sorgt beispielsweise der Wert `80%` dafür, dass der angezeigte Block nie breiter als 80% der Sectionbreite beträgt. Hier können auch Werte in `px` angegeben werden, wenn man einen exakten Wert wünscht. Die Info wird dabei allerdings nie größer als es die inneren Elemente benötigen. Ein einzelnes Wort würde bspw. selten die volle nutzbare Breite nutzen.

`data-full-width` gibt einen Wert in `px` an. Dieser beschreibt die maximale Bildschirmgröße, bei der der Infoblock die vollständige nutzbare Breite bekommt und somit `data-width` überschreibt. Hier darf keine Einheit ergänzt werden. Kommawerte sind möglich aber sollten nicht verwendet werden, da im Normalfall ein Fenster keine Pixelbruchteile als Größe haben kann: `data-full-width="250.5"`.
In dem gegebenen Beispiel würde bei allen Fenster/Bildschirmbreiten von weniger oder gleich 440px der Block immer die volle Sectionbreite nutzen können unabhängig von dem `data-width` wert. Erst ab Breiten über 440px würden die 80% greifen.

Ein Beispiel wurde in dem Markdown und HTML Template ergänzt.
